// ---------------------------------------------------------------------------
// Arcade — Prize Claw (hand-built walnut-and-brass claw cabinet)
//
// The first cabinet on the floor where PLAYER AIM CHANGES EXPECTED VALUE while
// the server stays authoritative and the outcome stays replayable.
//
// The shared geometry — the prize bed, the grip footprint, the exposure classes
// and the grab probability — lives in a browser-safe pure module:
//
//     src/features/arcade/lib/prize-claw-bed.ts
//
// The client imports it to build the cabinet and print the live grip readout;
// this module imports the same functions to resolve the drop. There is exactly
// one implementation of the maths. What the client can NEVER do is roll: the
// two hidden uniforms come from the private session seed and are computed here.
//
// ── TWO SEEDS, AND THEY MUST BE INDEPENDENT ─────────────────────────────────
//
//   bedSeed  PUBLIC   generated by validatePrizeClawConfig with its own call to
//                     generateArcadeSeed(), persisted in arcade_game_config,
//                     returned at session create. Drives prize placement.
//   seed     PRIVATE  generated inside createArcadeSession, revealed only at
//                     settle. Drives u1 (grab), u2 (hold), the script jitter
//                     and the payout rounding.
//
// bedSeed MUST NOT be derived from seed — not via deriveSubSeed, not via any
// function of it. arcade-rng.ts warns in-source that the 31-bit session seed is
// brute-forceable in seconds; if the public bed were a function of it, a client
// could recover the session seed from the bed, precompute both rolls, and only
// commit on winning rounds. This is the #1 correctness risk in the feature.
//
// ── NO TIMING SURFACE ───────────────────────────────────────────────────────
//
// The payout depends on (x, z) and the private seed. Nothing else. The
// 12-second positioning clock is client-side pacing and never reaches this
// resolver, so — unlike Skee-Ball and High Striker, which reconstruct outcomes
// from client timestamps — there is no clock-stretch, hidden-tab or
// Date.now()-tampering surface at all. Please do not add a timestamp later.
//
// ── RTP ─────────────────────────────────────────────────────────────────────
//
// pGrabMax(tier) × pHold(tier) × mult(tier) = ARCADE_RTP for every tier, so
// every prize has the same expected value at optimal play and prize choice is
// a pure variance choice. Advertised honestly as "97% on a clear prize's grip
// cross" — leaning and buried prizes pay less, and the readout says by how much
// before the player commits. See scripts/verify-prize-claw-rtp.ts.
// ---------------------------------------------------------------------------

import { roundArcadePayout } from '../arcade-payout';
import { deriveSubSeed, generateArcadeSeed, mulberry32 } from '../arcade-rng';
import {
  CLAW_BRUSH_BAND,
  CLAW_TIERS,
  clampToBed,
  clawAimAt,
  generatePrizeBed,
  isClawCabinetId,
  type ClawCabinetId,
  type ClawExposure,
  type ClawTierId,
  type PrizeBed,
} from '@/features/arcade/lib/prize-claw-bed';

// Re-exported so routes and the RTP gate have one import site for the whole
// cabinet, exactly as the spec calls for. The definitions themselves stay in
// the browser-safe module so the client can share them verbatim.
export * from '@/features/arcade/lib/prize-claw-bed';

/* ── Config ─────────────────────────────────────────────────────────────── */

export type PrizeClawConfig = {
  cabinet: ClawCabinetId;
  /** PUBLIC. Independent of the session seed. See the header. */
  bedSeed: number;
};

/**
 * Validate the create-session config and mint the bed.
 *
 * The client picks a cabinet and NOTHING else — a client-supplied bedSeed is
 * ignored outright, never echoed back, because letting a player choose the bed
 * would let them shop for a layout. The returned config is what
 * createArcadeSession persists and echoes to the client.
 */
export function validatePrizeClawConfig(config: unknown): PrizeClawConfig | null {
  if (!config || typeof config !== 'object') return null;
  const cabinet = (config as Record<string, unknown>).cabinet;
  if (!isClawCabinetId(cabinet)) return null;
  // Its own draw from the CSPRNG — never a function of the session seed.
  return { cabinet, bedSeed: generateArcadeSeed() };
}

/**
 * Read back a stored config. Defensive: a row written by an older or looser
 * build must not resolve into an undefined cabinet or a NaN bed.
 */
export function readPrizeClawConfig(config: unknown): PrizeClawConfig | null {
  if (!config || typeof config !== 'object') return null;
  const raw = config as Record<string, unknown>;
  if (!isClawCabinetId(raw.cabinet)) return null;
  const bedSeed = Number(raw.bedSeed);
  if (!Number.isFinite(bedSeed)) return null;
  return { cabinet: raw.cabinet, bedSeed: Math.floor(bedSeed) };
}

/* ── Resolution ─────────────────────────────────────────────────────────── */

export const CLAW_OUTCOMES = [
  'won',
  'slipped',
  'brushed',
  'missed',
  'empty',
] as const;
export type ClawOutcome = (typeof CLAW_OUTCOMES)[number];

/** Flat, matter-of-fact copy. No near-miss celebration, ever. */
export const CLAW_OUTCOME_LABELS: Record<ClawOutcome, string> = {
  won: 'Carried to the chute',
  slipped: 'Slipped at the rail',
  brushed: 'Brushed the shoulder',
  missed: 'Fingers closed empty',
  empty: 'Closed on bare felt',
};

export type ClawResolution = {
  /** The clamped commit point actually used. */
  point: { x: number; z: number };
  target: {
    index: number;
    tier: ClawTierId;
    tierName: string;
    exposure: ClawExposure;
    x: number;
    z: number;
  } | null;
  /** 0 dead-centre → 1 at the footprint edge. */
  aimError: number;
  /** The grab probability the roll was tested against. */
  grip: number;
  grabRoll: number;
  grabbed: boolean;
  holdChance: number;
  holdRoll: number;
  held: boolean;
  outcome: ClawOutcome;
  /** Payout multiplier — 0 unless the prize reached the chute. */
  multiplier: number;
};

/**
 * Resolve one drop. Pure given (seed, bed, x, z): the same inputs always give
 * the same outcome, which is what makes the retry path in the action route
 * safe and the post-round verification meaningful.
 *
 * Two hidden uniforms, each from its OWN sub-stream. Never one shared stream —
 * a reorder there would silently change historical outcomes.
 */
export function resolveClawDrop(
  seed: number,
  bed: PrizeBed,
  x: number,
  z: number,
): ClawResolution {
  const point = clampToBed(x, z);
  const aim = clawAimAt(bed, point.x, point.z);

  const grabRoll = mulberry32(deriveSubSeed(seed, 'prize-claw:grab'))();
  const holdRoll = mulberry32(deriveSubSeed(seed, 'prize-claw:hold'))();

  if (!aim.target) {
    return {
      point,
      target: null,
      aimError: 1,
      grip: 0,
      grabRoll,
      grabbed: false,
      holdChance: 0,
      holdRoll,
      held: false,
      outcome: 'empty',
      multiplier: 0,
    };
  }

  const { prize, aimError } = aim.target;
  const tier = CLAW_TIERS[prize.tier];
  const grip = aim.grip;
  const grabbed = grabRoll < grip;
  const held = grabbed && holdRoll < tier.holdChance;

  let outcome: ClawOutcome;
  if (grabbed) {
    outcome = held ? 'won' : 'slipped';
  } else if (grabRoll < grip + CLAW_BRUSH_BAND) {
    // Presentation band only — pays exactly 0, identically to a miss, and is
    // derived from the same revealed roll so the player can check it.
    outcome = 'brushed';
  } else {
    outcome = 'missed';
  }

  return {
    point,
    target: {
      index: prize.index,
      tier: prize.tier,
      tierName: tier.name,
      exposure: prize.exposure,
      x: prize.x,
      z: prize.z,
    },
    aimError,
    grip,
    grabRoll,
    grabbed,
    holdChance: tier.holdChance,
    holdRoll,
    held,
    outcome,
    multiplier: outcome === 'won' ? tier.multiplier : 0,
  };
}

/* ── The animation, as data ─────────────────────────────────────────────── */

/**
 * Base phase lengths in ms. The client plays the script the server sends, so
 * both sides agree on the timeline and a tab-switch can resync by elapsed time
 * rather than by guesswork. Same precedent as generateRaceScript in
 * src/server/arcade/derby/derby-shared.ts.
 */
export const CLAW_PHASE_MS = {
  descend: 900,
  close: 420,
  grip: 260,
  lift: 1_100,
  travel: 900,
  release: 380,
  chute: 620,
} as const;

export type ClawScript = {
  outcome: ClawOutcome;
  descendMs: number;
  closeMs: number;
  gripMs: number;
  liftMs: number;
  /** 0 on every outcome except `won`. */
  travelMs: number;
  releaseMs: number;
  chuteMs: number;
  totalMs: number;
  /** Fraction of the lift at which the fingers relax. Null unless `slipped`. */
  slipAtT: number | null;
  /** Topple keys for a brush — yaw and roll in radians, settle time in ms. */
  toppleYaw: number;
  toppleRoll: number;
  toppleMs: number;
  /** Bounce heights (world units) as the prize settles back onto the felt. */
  bounce: number[];
  /** Felt-fibre puff intensity at the close, 0..1. */
  dust: number;
};

/** Deterministic per-round choreography, from its own sub-stream. */
export function generateClawScript(
  seed: number,
  resolution: ClawResolution,
): ClawScript {
  const rng = mulberry32(deriveSubSeed(seed, 'prize-claw:script'));
  const jitter = (base: number, spread = 0.06) =>
    Math.round(base * (1 + (rng() * 2 - 1) * spread));

  const won = resolution.outcome === 'won';
  const descendMs = jitter(CLAW_PHASE_MS.descend);
  const closeMs = jitter(CLAW_PHASE_MS.close);
  const gripMs = jitter(CLAW_PHASE_MS.grip);
  const liftMs = jitter(CLAW_PHASE_MS.lift);
  const travelMs = won ? jitter(CLAW_PHASE_MS.travel) : 0;
  const releaseMs = won ? jitter(CLAW_PHASE_MS.release) : 0;
  const chuteMs = won ? jitter(CLAW_PHASE_MS.chute) : 0;

  const slipAtT =
    resolution.outcome === 'slipped' ? 0.28 + rng() * 0.54 : null;
  const brushed = resolution.outcome === 'brushed';
  const toppleYaw = brushed ? (rng() * 2 - 1) * 0.9 : 0;
  const toppleRoll = brushed ? 0.35 + rng() * 0.5 : 0;
  const toppleMs = brushed ? jitter(520, 0.18) : 0;
  const bounce =
    resolution.outcome === 'slipped' || brushed
      ? [0.12 + rng() * 0.06, 0.05 + rng() * 0.03, 0.02 + rng() * 0.015]
      : [];

  return {
    outcome: resolution.outcome,
    descendMs,
    closeMs,
    gripMs,
    liftMs,
    travelMs,
    releaseMs,
    chuteMs,
    totalMs:
      descendMs + closeMs + gripMs + liftMs + travelMs + releaseMs + chuteMs,
    slipAtT,
    toppleYaw,
    toppleRoll,
    toppleMs,
    bounce,
    dust: 0.4 + rng() * 0.6,
  };
}

/* ── Payout ─────────────────────────────────────────────────────────────── */

/**
 * Tickets for a resolved drop. The multiplier is the tier's face value; the
 * house edge lives in the grab/hold probabilities (which are built from it),
 * so nothing is discounted a second time here. The only adjustment is the
 * shared unbiased fractional-ticket rounding.
 */
export function computePrizeClawPayout(
  wager: number,
  resolution: ClawResolution,
  seed: number,
): number {
  if (resolution.outcome !== 'won' || resolution.multiplier <= 0) return 0;
  return roundArcadePayout(
    wager * resolution.multiplier,
    seed,
    `prize-claw:${resolution.target?.tier ?? 'x'}`,
  );
}

/* ── One-call resolution used by both the drop and the replay path ──────── */

export type PrizeClawRound = {
  config: PrizeClawConfig;
  bed: PrizeBed;
  resolution: ClawResolution;
  script: ClawScript;
};

/**
 * Regenerate the bed from the stored config and resolve a committed point.
 * Used by the live drop AND by the idempotent replay path, so a retried POST
 * reproduces the identical outcome without touching the wallet.
 */
export function playPrizeClawDrop(
  storedConfig: unknown,
  seed: number,
  x: number,
  z: number,
): PrizeClawRound | null {
  const config = readPrizeClawConfig(storedConfig);
  if (!config) return null;
  const bed = generatePrizeBed(config.bedSeed, config.cabinet);
  const resolution = resolveClawDrop(seed, bed, x, z);
  return { config, bed, resolution, script: generateClawScript(seed, resolution) };
}

/** The choice persisted by recordArcadeChoice — the committed point, nothing else. */
export type PrizeClawChoice = { x: number; z: number };

export function readPrizeClawChoice(choice: unknown): PrizeClawChoice | null {
  if (!choice || typeof choice !== 'object') return null;
  const raw = choice as Record<string, unknown>;
  const { x, z } = raw;
  if (
    typeof x !== 'number' ||
    !Number.isFinite(x) ||
    typeof z !== 'number' ||
    !Number.isFinite(z)
  ) {
    return null;
  }
  const clamped = clampToBed(x, z);
  if (clamped.x !== x || clamped.z !== z) return null;
  return { x, z };
}
