#!/usr/bin/env python3
"""Outline the tixy.lol wordmark from Gabarito Black.

Writes src/features/brand/tixy-wordmark-outline.ts: SVG path data for the
letters and for the red full stop, in font units (1000 per em), with the
baseline at y = 0 and y pointing down. Nothing needs the font at runtime.

The text is shaped with HarfBuzz at wght 900, so Gabarito's own kerning
applies, then tracked by -0.02em (PLAN.md: no tighter than -0.02em).

Run it from the repo root. The tools live in a throwaway virtualenv, not in
package.json:

    python3 -m venv /tmp/tixy-brand-venv
    /tmp/tixy-brand-venv/bin/pip install fonttools brotli uharfbuzz
    /tmp/tixy-brand-venv/bin/python scripts/brand/outline-wordmark.py
    npx tsx scripts/brand/build-brand-assets.tsx

The font defaults to the OFL Gabarito woff2 kept with the rebrand docs.
Pass --font to use another copy.
"""

from __future__ import annotations

import argparse
import io
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FONT = ROOT / 'public/fonts/brand/gabarito-latin-variable.woff2'
OUT = ROOT / 'src/features/brand/tixy-wordmark-outline.ts'

TEXT = 'tixy.lol'
DOT_INDEX = TEXT.index('.')
WEIGHT = 900
TRACKING_EM = -0.02


def fmt(value: float) -> str:
    text = f'{value:.1f}'
    if text.endswith('.0'):
        text = text[:-2]
    return '0' if text == '-0' else text


class RoundedSVGPathPen(SVGPathPen):
    """SVGPathPen with one decimal place, which is 0.1% of an em."""

    def __init__(self, glyph_set):
        super().__init__(glyph_set, ntos=fmt)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--font', type=Path, default=DEFAULT_FONT)
    parser.add_argument('--out', type=Path, default=OUT)
    args = parser.parse_args()

    if not args.font.exists():
        raise SystemExit(f'Gabarito not found at {args.font}. Pass --font.')

    font = TTFont(args.font)
    font.flavor = None
    instantiateVariableFont(font, {'wght': WEIGHT}, inplace=True)
    buffer = io.BytesIO()
    font.save(buffer)
    data = buffer.getvalue()
    font = TTFont(io.BytesIO(data))

    upem = font['head'].unitsPerEm
    hhea = font['hhea']
    glyph_set = font.getGlyphSet()
    glyph_order = font.getGlyphOrder()

    hb_font = hb.Font(hb.Face(data))
    hb_buffer = hb.Buffer()
    hb_buffer.add_str(TEXT)
    hb_buffer.guess_segment_properties()
    hb.shape(hb_font, hb_buffer, {'kern': True, 'liga': False})

    tracking = TRACKING_EM * upem
    pen_x = 0.0
    ink_pen = RoundedSVGPathPen(glyph_set)
    dot_pen = RoundedSVGPathPen(glyph_set)
    bounds = BoundsPen(glyph_set)

    for info, pos in zip(hb_buffer.glyph_infos, hb_buffer.glyph_positions):
        name = glyph_order[info.codepoint]
        x = pen_x + pos.x_offset
        y = pos.y_offset
        # Font units are y-up. Flip so the SVG baseline sits at y = 0.
        transform = (1, 0, 0, -1, x, -y)
        target = dot_pen if info.cluster == DOT_INDEX else ink_pen
        glyph_set[name].draw(TransformPen(target, transform))
        glyph_set[name].draw(TransformPen(bounds, transform))
        pen_x += pos.x_advance + tracking

    x_min, y_min, x_max, y_max = bounds.bounds

    source = f"""// Generated by scripts/brand/outline-wordmark.py. Do not edit by hand.
// "{TEXT}" in Gabarito {WEIGHT}, kerned, tracked {TRACKING_EM}em.
// Font units ({upem} per em), baseline at y = 0, y down.
// Gabarito is (c) The Gabarito Project Authors, SIL Open Font License 1.1.

export const TIXY_WORDMARK_OUTLINE = {{
  text: '{TEXT}',
  unitsPerEm: {upem},
  ascender: {hhea.ascent},
  descender: {hhea.descent},
  bounds: {{ xMin: {fmt(x_min)}, yMin: {fmt(y_min)}, xMax: {fmt(x_max)}, yMax: {fmt(y_max)} }},
  ink: '{ink_pen.getCommands()}',
  dot: '{dot_pen.getCommands()}',
}} as const;
"""
    args.out.write_text(source)
    print(f'wrote {args.out.relative_to(ROOT)}: {TEXT}, {fmt(x_max - x_min)} x {fmt(y_max - y_min)} units')


if __name__ == '__main__':
    main()
