// The achievement catalog. Source of truth in code (seeded into DB for global
// counts + admin visibility, like cosmetics). Tiered tracks are generated by
// the `series()` helper so ~30 tracks × 5 tiers + standalones + secrets stay
// DRY. Each tier of a series is its own achievement id ("snake-score-3").
import {
  ARCADE_FLOOR_GROUPS,
  isOnFloor,
} from '@/features/arcade/components/arcade-game-registry';
import type { StoreRarity } from '@/features/arcade/lib/rewards';
import {
  GLOBAL,
  MP,
  DAILY,
  gameStat,
  groupPlayedStat,
  secretStat,
} from '@/server/arcade/stats/stat-keys';
import { badgeIconFor } from './badges';
import {
  TIER_LABELS,
  type AchievementCategory,
  type AchievementDef,
} from './types';

const TIER_XP = [120, 250, 500, 1000, 2000];
const TIER_RARITY: StoreRarity[] = ['common', 'common', 'rare', 'epic', 'legendary'];

/** An achievement's display name: a capital first letter and the rest in
 *  lowercase ("Hello, world", "Serpentine 3"). Ids never change with it. */
function sentenceCase(name: string): string {
  const lower = name.toLowerCase();
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}

type SeriesOpts = {
  id: string;
  name: string;
  category: AchievementCategory;
  stat: string;
  thresholds: number[]; // up to 5, ascending (descending for direction:'low')
  direction?: 'low'; // lower stat is better -> lte condition
  /** Unused. Badges are drawn from the id (badges.ts); the per-achievement PNGs are no longer shown. */
  icon?: string;
  /** Store item id granted at the final tier. */
  topCosmetic?: string;
  blurb: (threshold: number, tier: number) => string;
  /** Off the floor whatever its game: listed only for players who earned it. */
  retired?: boolean;
};

/* A series belongs to the game its stat is named for ("snake.best" -> snake).
   Cross-game stats (global, mp, daily) belong to no game. */
const NO_GAME_SCOPES = new Set(['global', 'mp', 'daily']);
function gameOfStat(stat: string): string | undefined {
  const scope = stat.split('.')[0];
  return NO_GAME_SCOPES.has(scope) ? undefined : scope;
}

function series(opts: SeriesOpts): AchievementDef[] {
  const game = gameOfStat(opts.stat);
  return opts.thresholds.map((threshold, i) => {
    const isTop = i === opts.thresholds.length - 1;
    return {
      id: `${opts.id}-${i + 1}`,
      seriesId: opts.id,
      tier: i + 1,
      tierLabel: TIER_LABELS[i],
      name: `${sentenceCase(opts.name)} ${i + 1}`,
      description: opts.blurb(threshold, i + 1),
      category: opts.category,
      hidden: false,
      rarity: TIER_RARITY[i],
      xp: TIER_XP[i],
      cosmeticId: isTop ? opts.topCosmetic : undefined,
      icon: badgeIconFor(`${opts.id}-${i + 1}`, i + 1, opts.id),
      game,
      retired: opts.retired,
      condition:
        opts.direction === 'low'
          ? { stat: opts.stat, lte: threshold }
          : { stat: opts.stat, gte: threshold },
    };
  });
}

type StandaloneOpts = {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  rarity: StoreRarity;
  xp: number;
  condition: AchievementDef['condition'];
  icon?: string;
  cosmeticId?: string;
  hidden?: boolean;
  hint?: string;
  secretTriggerKey?: string;
  retired?: boolean;
};

function standalone(opts: StandaloneOpts): AchievementDef {
  return {
    id: opts.id,
    tier: 0,
    name: sentenceCase(opts.name),
    description: opts.description,
    category: opts.category,
    hidden: opts.hidden ?? false,
    rarity: opts.rarity,
    xp: opts.xp,
    cosmeticId: opts.cosmeticId,
    icon: badgeIconFor(opts.id, 0),
    condition: opts.condition,
    hint: opts.hint,
    secretTriggerKey: opts.secretTriggerKey,
    retired: opts.retired,
  };
}

/** A secret/easter-egg gated on a `secret.<key>` trigger counter reaching `count`. */
function secret(opts: {
  id: string;
  name: string;
  description: string;
  triggerKey: string;
  count?: number;
  rarity?: StoreRarity;
  xp?: number;
  cosmeticId?: string;
  hint?: string;
  retired?: boolean;
}): AchievementDef {
  return standalone({
    retired: opts.retired,
    id: opts.id,
    name: opts.name,
    description: opts.description,
    category: 'secret',
    rarity: opts.rarity ?? 'epic',
    xp: opts.xp ?? 400,
    hidden: true,
    hint: opts.hint,
    icon: 'secret',
    cosmeticId: opts.cosmeticId,
    secretTriggerKey: opts.triggerKey,
    condition: { stat: secretStat(opts.triggerKey), gte: opts.count ?? 1 },
  });
}

const ms = (n: number) => (n >= 1000 ? `${(n / 1000).toFixed(n % 1000 ? 1 : 0)}s` : `${n}ms`);

// ── Tiered series ──────────────────────────────────────────────────────────
const SERIES: AchievementDef[] = [
  // Solo score games.
  ...series({ id: 'snake-score', name: 'Serpentine', category: 'arcade', stat: gameStat('snake', 'best'), thresholds: [100, 300, 600, 900, 1200], topCosmetic: 'ach-snake', blurb: (t) => `Score ${t} in snake.` }),
  // Flappy bird, back on the floor in October 2026. scripts/sim-flappy-tiers.ts
  // plays the shared sim with a bot that aims for the gap's middle and taps
  // with a timing error (novice 60 ms, casual 42, good 30, strong 21, expert
  // 14), 1,000 runs each. Best of 10 runs (a first week): novice 13, casual
  // 34, good 126. Best of 50: casual 54, good 190. Tier I is a novice's first
  // sessions, II a casual week, III a casual player's best of 50, IV a good
  // player's week, and V a good player's best of 50, where 150 was. Earned
  // tiers stay earned.
  ...series({ id: 'flappy-score', name: 'Flap Happy', category: 'arcade', stat: gameStat('flappy-bird', 'best'), thresholds: [10, 30, 60, 100, 200], blurb: (t) => `Pass ${t} pipes in flappy bird.` }),
  // 2048 2026-10 retune. scripts/sim-achievement-thresholds.ts plays the game's
  // rules with a 2-ply bot that plays a random move with probability eps (novice
  // .35, casual .16, good .06, strong .02, expert .004), 40 runs each. Run p50:
  // novice 256, casual 512, good 1024, strong 1024, expert 2048. Best of 10 runs
  // (a first week): novice 512, casual 1024, strong 2048, expert 4096. 128 to 1024 are a
  // novice's first sessions to a casual's first week and 2048 is a good player's
  // best of 100 runs. 4096 was this series' top and also Beyond 2048's whole
  // condition, so the series stops at 2048 and Beyond 2048 keeps 4096.
  ...series({ id: '2048-tile', name: 'Power of Two', category: 'arcade', stat: gameStat('2048', 'highest_tile'), thresholds: [128, 256, 512, 1024, 2048], topCosmetic: 'ach-2048', blurb: (t) => `Reach the ${t} tile in 2048.` }),
  ...series({ id: 'tetris-lines', name: 'Line Cook', category: 'arcade', stat: gameStat('tetris', 'lines'), thresholds: [50, 250, 1000, 5000, 20000], topCosmetic: 'ach-tetris', blurb: (t) => `Clear ${t.toLocaleString()} total lines in Tetris.` }),
  ...series({ id: 'typing-wpm', name: 'Wordsmith', category: 'arcade', stat: gameStat('typing-test', 'best_wpm'), thresholds: [60, 80, 100, 120, 140], topCosmetic: 'ach-typing', blurb: (t) => `Type at ${t} WPM.` }),
  // Breakout 2026-07 retune: a level is worth ~1.8-3.6k (row points 20-70 × ~37-58
  // bricks + clear bonus), so the old tier 5 (15k ≈ 6 levels) was only a solid run;
  // experts on 3 lives reach ~10+ levels (~28-46k). Top tier ≈ an 8-9 level run.
  ...series({ id: 'breakout-score', name: 'Brickbuster', category: 'arcade', stat: gameStat('breakout', 'best'), thresholds: [1000, 3000, 8000, 15000, 25000], blurb: (t) => `Score ${t.toLocaleString()} in Breakout.` }),
  ...series({ id: 'stack-score', name: 'Skyscraper', category: 'arcade', stat: gameStat('stack', 'best'), thresholds: [10, 25, 50, 100, 200], blurb: (t) => `Stack ${t} blocks high.` }),
  // Gem Swap 2026-07 retune: strictly 60s runs with input locked during ~420ms+ match
  // animations (~65-70 swaps max) and ~30-130 pts/swap with no cross-swap combo, so
  // the expert ceiling is ~10-15k — the old 20k/50k top tiers were unreachable.
  ...series({ id: 'gem-score', name: 'Gem Hoarder', category: 'arcade', stat: gameStat('gem-swap', 'best'), thresholds: [1000, 3000, 6000, 9000, 12000], blurb: (t) => `Score ${t.toLocaleString()} in Gem Swap.` }),
  ...series({ id: 'bubble-score', name: 'Gumball Glory', category: 'arcade', stat: gameStat('bubble-shooter', 'best'), thresholds: [1000, 3000, 8000, 20000, 50000], blurb: (t) => `Score ${t.toLocaleString()} in Gumball Drop.` }),
  ...series({ id: 'sky-score', name: "Sky's the Limit", category: 'arcade', stat: gameStat('sky-climber', 'best'), thresholds: [100, 300, 700, 1500, 3000], blurb: (t) => `Climb to ${t.toLocaleString()} in Sky Climber.` }),
  // Gopher 2026-07 combo-scoring rescale (bonk count → points, ~20x): a theoretical
  // perfect 60s run ≈ 5,300; realistic elite ≈ 3,000-3,600, so top tier sits at 3,500.
  ...series({ id: 'gopher-score', name: 'Whack Master', category: 'arcade', stat: gameStat('gopher', 'best'), thresholds: [200, 600, 1500, 2500, 3500], blurb: (t) => `Score ${t.toLocaleString()} in Gopher.` }),
  ...series({ id: 'sequence-score', name: 'Total Recall', category: 'arcade', stat: gameStat('sequence', 'best'), thresholds: [5, 10, 15, 22, 30], blurb: (t) => `Reach level ${t} in Sequence.` }),
  // Swerve 2026-07 runner rework (1/row + close-call bonuses, ~2.3 pts/row deep):
  // old tiers were unreachable; top tier ≈ a sustained ~6-7 minute expert run.
  ...series({ id: 'swerve-score', name: 'Drift King', category: 'arcade', stat: gameStat('swerve', 'best'), thresholds: [40, 120, 350, 900, 2000], blurb: (t) => `Score ${t.toLocaleString()} in Swerve.` }),
  // Ricochet 2026-10 retune, back on the floor. The 2026-07 tiers (10 to 300)
  // were set from a best of 377 the old check couldn't verify: the server
  // validated wall events the client sent and never replayed the bird. It does
  // now (ricochet-replay.ts), and the physics is the old physics, so a score
  // means what it did. scripts/sim-ricochet.ts plays the real engine with a bot
  // per skill (aim error, reaction lag, missed taps; 300 runs each). Run p50:
  // novice 3, casual 7, good 15, strong 28, expert 44. Best of 10 runs (a first
  // week): 11, 17, 32, 53, 78. Best of 100 (a few weeks): 16, 27, 41, 72, 128.
  // Tier I (10) is a novice's first session, II (25) a casual's few weeks and a
  // good player's first week, III (50) a strong player's first week, IV (90) a
  // strong player's few weeks and V (125) an expert's few weeks. Held tiers stay
  // held; ids are unchanged and the old 30, 75, 150 and 300 thresholds are gone.
  ...series({ id: 'ricochet-score', name: 'Ricochet', category: 'arcade', stat: gameStat('ricochet', 'best'), thresholds: [10, 25, 50, 90, 125], blurb: (t) => `Clear ${t} walls in Ricochet.` }),
  // Tumbler 2026-07 precision-scoring rework (~2-4 pts/pin, route cap 4000): the old
  // tiers were unreachable; retuned to the new points scale (top ≈ a ~200-pin run).
  ...series({ id: 'tumbler-score', name: 'On a Roll', category: 'arcade', stat: gameStat('tumbler', 'best'), thresholds: [25, 75, 150, 300, 600], blurb: (t) => `Score ${t.toLocaleString()} in Tumbler.` }),
  // High Striker 2026-07: score is points (1 graze / 2 crushed / 3 streak / 5
  // bell per cleared round; route cap 2500). Scale mirrors Tumbler's points
  // economy — top tier ≈ a sustained ~200-round expert run.
  // High Striker rules 2 (five swings, at most 25 points) can't reach Strongman's
  // 25 to 600, which were set for the unbounded run. Strongman is retired, ids
  // unchanged, so holders keep it on the retired shelf. Bell Ringer replaces it
  // on `high-striker.best_five`, the best score of a five-swing run, written by
  // the score route (stats/deltas.ts). Thresholds are percentiles of
  // scripts/verify-high-striker-replay.ts' 10,000 runs per skill (a player who
  // aims every hold at the gauge's peak, off by a normal timing error): tier I is
  // the casual 25th percentile (10), II the casual 75th (14), III the good
  // median (17), IV the strong 75th (21) and V the expert 75th (25, five bells).
  // The stat is the best run ever, so each is easier in practice than its
  // percentile of single runs; the verifier fails if the thresholds drift.
  ...series({ id: 'high-striker-score', name: 'Strongman', category: 'arcade', stat: gameStat('high-striker', 'best'), thresholds: [25, 75, 150, 300, 600], retired: true, blurb: (t) => `Score ${t.toLocaleString()} in high striker.` }),
  // High striker rules 3 (October 2026, the endless tower) retires Bell Ringer
  // by hand as well, and migration 0073 removed every player's Strongman and
  // Bell Ringer rows and their stats (HIGH_STRIKER.md, "Achievements"), so
  // both series are listed for no one. The ids stay so stored keys never
  // change.
  ...series({ id: 'high-striker-bell-ringer', name: 'Bell Ringer', category: 'arcade', stat: gameStat('high-striker', 'best_five'), thresholds: [10, 14, 17, 21, 25], retired: true, icon: 'high-striker-score', blurb: (t) => `Score ${t} in a five-swing high striker run.` }),
  // The endless series. Iron Arm reads the deepest run (hits before the miss)
  // and Dead Centre the longest run of bells in a row, both written by the
  // score route (stats/deltas.ts). Tiers are read off
  // scripts/verify-high-striker-replay.ts' simulated hands (best of ten runs,
  // a first week): Iron Arm I is a new player's, II a casual's, III a good
  // player's, IV a strong one's and V an expert's; Dead Centre I is a
  // casual's, II a good player's, III a strong one's, IV an expert's and V
  // past that. The verifier fails if they drift.
  ...series({ id: 'high-striker-depth', name: 'Iron Arm', category: 'arcade', stat: gameStat('high-striker', 'endless_depth'), thresholds: [10, 25, 50, 75, 120], blurb: (t) => `Clear ${t} swings in one high striker run.` }),
  ...series({ id: 'high-striker-bells', name: 'Dead Centre', category: 'arcade', stat: gameStat('high-striker', 'endless_streak'), thresholds: [3, 6, 10, 15, 25], blurb: (t) => `Ring the bell ${t} times in a row in high striker.` }),
  // Log Splitter 2026-07: score is chops. A safe-side bot at the 60ms cadence floor
  // tops out at ~649; a realistic sustained-expert run (~7-8 chops/s) is ~180-230.
  // Top tier 150 ≈ 65% of that expert ceiling (a hard-but-provably-achievable
  // ~6.5 chops/s sustained), with earlier tiers spaced for a smooth climb.
  ...series({ id: 'log-splitter-score', name: 'Timberjack', category: 'arcade', stat: gameStat('log-splitter', 'best'), thresholds: [15, 40, 75, 110, 150], blurb: (t) => `Chop ${t.toLocaleString()} logs in Log Splitter.` }),
  // Knife Booth 2026-07: score is points (1/knife, +5/fruit, depth-scaled stage
  // clears). A human-timing bot over 500 seeds: good runs (σ≈40ms) ≈ 130-190;
  // sustained-expert (σ≈28ms) reaches p90≈264, p99≈333; a god-tier σ≈18ms run
  // reaches p75≈325 / max≈524. Top tier 300 sits at expert p90-p99 (reliably
  // cleared by a god-tier run) — hard-but-provably-achievable; earlier tiers
  // trace the good→strong→expert climb.
  ...series({ id: 'knife-booth-score', name: 'Sharp Shooter', category: 'arcade', stat: gameStat('knife-booth', 'best'), thresholds: [25, 75, 150, 225, 300], blurb: (t) => `Score ${t.toLocaleString()} in Knife Booth.` }),
  // Melon Chop 2026-07: score is points (fruit base 10, combo-multiplied up to ×3
  // per stroke) over a 60s blitz. A human-ish swipe bot over 500 seeds: casual
  // p50≈820 (bombs end most runs), good p50≈980/p90≈2420, expert p50≈1790/p75≈2770,
  // near-perfect p50≈2920/p90≈3270/p99≈3610 (exact ceiling ≈7400). Top tier 2400
  // sits at expert-p75 / good-p90 / god-p50 (~67% of the near-perfect ceiling) —
  // hard-but-provably-achievable; earlier tiers trace the casual→good→expert climb.
  ...series({ id: 'melon-chop-score', name: 'Fruit Slicer', category: 'arcade', stat: gameStat('melon-chop', 'best'), thresholds: [250, 600, 1100, 1700, 2400], blurb: (t) => `Score ${t.toLocaleString()} in Melon Chop.` }),
  // Skee-Ball 2026-10: score is points over a 9-ball frame plus up to 3 bonus
  // balls from the 100 pockets (rings 10 to 50, x2 for the lit ring, x3 late).
  // scripts/sim-skeeball-thresholds.ts throws the real replay with a bot that
  // picks each ball's best throw for its lit ring and has Gaussian error on aim
  // and power, 400 seeds per skill. Re-run on #67's physics: medians novice 300,
  // casual 330, good 450, strong 580, expert 830 (best frame 1,500). The bot knows
  // where every ring is, so it overstates a person. Top tier 600 is 72% of the
  // expert median, about a good player's best tenth; 200 is a novice's worst
  // tenth, and the steps between are even.
  ...series({ id: 'skee-ball-score', name: 'Ring Leader', category: 'arcade', stat: gameStat('skee-ball', 'best'), thresholds: [200, 300, 400, 500, 600], blurb: (t) => `Score ${t.toLocaleString()} in a skee-ball frame.` }),
  // Ticket stop 2026-10 (rules 2, the lock): score is hits before the first miss,
  // on the lock's fixed level ramp. scripts/verify-ticket-stop-replay.ts throws
  // the real replay with simulated players (normal timing error of the given SD,
  // slower to read a dot that arrives fast, a small slip rate), 4,000 runs per
  // skill. Score p50 / p90: first go (60 ms) 2 / 9, new (48 ms) 5 / 16, casual
  // (34 ms) 17 / 40, good (24 ms) 47 / 95, sharp (15 ms) 150 / 224. Tiers are
  // a player's best run, so they sit near these single-run marks: 10 is the new
  // player's median to p90, 25 a casual p50 to p75, 50 a good median, 100 a good
  // p90, and the top tier 150 a sharp player's median (a hand that misses the
  // dot by 15 ms or less, which is the sharpest the verifier's play check
  // models). Stat is `lock_best`, not `best`: rules 1 wrote `best` on a 0 to
  // 300 scale and it must not unlock these.
  // Ring toss 2026-10: score is points from ten rings (rows 10 to 50, the gold
  // bottle 100). scripts/verify-ring-toss-replay.ts plays whole rounds with
  // simulated hands (flick speed, finger placement, slant and hook noise), 120
  // per skill: casual p75 380, good p50 400 and p90 600, sharp p50 600 and p90
  // 830. Tiers are a best round: 250 a casual player's good round, 400 a good
  // median, 550 a good player stretching, 700 a sharp player's good round, 850
  // a sharp best of ten. Ids never change.
  ...series({ id: 'ring-toss-score', name: 'Ringer', category: 'arcade', stat: gameStat('ring-toss', 'best'), thresholds: [250, 400, 550, 700, 850], blurb: (t) => `Score ${t.toLocaleString()} in a ring toss round.` }),
  // Derby 2026-10: races won. scripts/sim-derby.ts races each skill against
  // seeded bot fields: a casual player wins about 1% of races, a good one 11%
  // and a sharp one 60%. Tiers: a first win, 5 (a good player's first week),
  // 20, 50 and 120 (a sharp regular). Ids never change.
  ...series({ id: 'derby-wins', name: 'Wire to wire', category: 'arcade', stat: gameStat('derby', 'wins'), thresholds: [1, 5, 20, 50, 120], blurb: (t) => (t === 1 ? 'Win a derby race.' : `Win ${t.toLocaleString()} derby races.`) }),
  ...series({ id: 'ticket-stop-score', name: 'Lock Picker', category: 'arcade', stat: gameStat('ticket-stop', 'lock_best'), thresholds: [10, 25, 50, 100, 150], icon: 'reaction-ms', blurb: (t) => `Score ${t.toLocaleString()} in ticket stop.` }),
  // Tin Duck rules 2 (a thirty second gallery: scores of about 60 to 250) can't
  // reach Duck Hunter's 375 to 625, and would hand out its first two tiers
  // for nothing, which were set for the 75 s popup range. Duck Hunter is retired, ids unchanged, so holders keep it on the
  // retired shelf. Sharpshooter replaces it on `tin-duck.best_gallery`, the best
  // thirty second run, written by the score route (stats/deltas.ts). Thresholds
  // are percentiles of scripts/verify-tin-duck-gallery.ts' runs per skill: tier I
  // is the casual 25th percentile, II the casual 75th, III the good median, IV the
  // strong 75th and V the expert 75th. The stat is the best run ever, so each is
  // easier in practice than its percentile of single runs; the verifier fails if
  // the thresholds drift.
  ...series({ id: 'tin-duck-score', name: 'Duck Hunter', category: 'arcade', stat: gameStat('tin-duck', 'best'), thresholds: [100, 250, 375, 500, 625], retired: true, blurb: (t) => `Score ${t.toLocaleString()} in tin duck gallery.` }),
  ...series({ id: 'tin-duck-gallery-score', name: 'Sharpshooter', category: 'arcade', stat: gameStat('tin-duck', 'best_gallery'), thresholds: [58, 74, 128, 173, 194], icon: 'tin-duck-score', blurb: (t) => `Score ${t} in a thirty second tin duck gallery round.` }),
  // Boardwalk Hop 2026-07: score is furthest row + close-call bonuses (endless,
  // difficulty-ramped like swerve). A greedy survivor bot over 2000 seeds/skill:
  // casual p50≈152, good p50≈235, strong p50≈336, expert p50≈474/p90≈1061/p99≈1964,
  // perfect p90≈2035/max≈6162. Top tier 1400 ≈ 69% of the perfect-p90 ceiling
  // (a sustained expert clears it) — hard-but-provably-achievable; earlier tiers
  // trace the casual→good→strong→expert climb.
  ...series({ id: 'boardwalk-hop-score', name: 'Boardwalk Bounder', category: 'arcade', stat: gameStat('boardwalk-hop', 'best'), thresholds: [50, 150, 400, 850, 1400], blurb: (t) => `Score ${t.toLocaleString()} in Boardwalk Hop.` }),
  // Gunrush 2026-08: score is row payouts down an endless seeded squad runner
  // (gate rows 10 + 4×row, wave rows far more), so the scale runs an order of
  // magnitude above the other quick-play games. Measured by
  // scripts/verify-gunrush-replay.ts: a casual run ends ~2,000-8,000, a strong
  // run ~20,000-30,000, and perfect greedy play across 60 seeds tops out at
  // 66,165 (rows p50=85, max=120) before the wave HP curve outruns the DPS
  // ceiling. Top tier 45,000 ≈ 68% of that measured perfect ceiling — hard but
  // provably achievable; earlier tiers trace the casual→good→strong→expert climb.
  // No topCosmetic: no gunrush achievement cosmetic exists yet.
  ...series({ id: 'gunrush-score', name: 'Squad Leader', category: 'arcade', stat: gameStat('gunrush', 'best'), thresholds: [3000, 9000, 20000, 32000, 45000], blurb: (t) => `Score ${t.toLocaleString()} in Gunrush.` }),
  // Math 2026-07 retune: 60s sprint whose difficulty ramp hits 2-digit × 2-digit by
  // problem ~24 (~3-4s each even for experts), so a sustained-elite ceiling is ~30-35
  // correct. Live all-time best is 25; the old [20..400] tiers 3-5 were impossible.
  ...series({ id: 'math-score', name: 'Mathlete', category: 'arcade', stat: gameStat('math', 'best'), thresholds: [10, 15, 20, 25, 35], blurb: (t) => `Score ${t} in Math.` }),
  // Blitz Tactics 2026-07: score is puzzles solved in a 5-min rush over a seeded,
  // machine-verified mate-puzzle ladder that escalates from easy mate-in-1s to
  // mate-in-2s. Solving rate for a strong player ≈ 3-6/min but the ladder slows
  // sharply as mate-in-2 bands arrive, so a sustained-expert ceiling is ~28-32
  // solved. Top tier 28 ≈ a hard-but-achievable elite run (a strong player clears
  // it), earlier tiers trace casual→good→strong→expert. (No bot: the ceiling is
  // reasoned like sudoku/math from per-puzzle solve time × the 5-min clock.)
  ...series({ id: 'blitz-tactics-score', name: 'Tactician', category: 'arcade', stat: gameStat('blitz-tactics', 'best'), thresholds: [5, 11, 17, 23, 28], blurb: (t) => `Solve ${t} puzzles in Blitz Tactics.` }),

  // Time-based (lower is better).
  ...series({ id: 'reaction-ms', name: 'Reflexes', category: 'arcade', stat: gameStat('reaction-time', 'best_ms'), thresholds: [400, 300, 250, 200, 160], direction: 'low', topCosmetic: 'ach-reaction', blurb: (t) => `React in under ${ms(t)}.` }),
  ...series({ id: 'sudoku-ms', name: 'Number Cruncher', category: 'arcade', stat: gameStat('sudoku', 'best_ms'), thresholds: [600000, 420000, 300000, 180000, 120000], direction: 'low', blurb: (t) => `Solve a Sudoku in under ${ms(t)}.` }),
  ...series({ id: 'minesweeper-ms', name: 'Bomb Squad', category: 'arcade', stat: gameStat('minesweeper', 'best_ms'), thresholds: [300000, 180000, 120000, 60000, 30000], direction: 'low', blurb: (t) => `Clear Minesweeper in under ${ms(t)}.` }),
  // Punch Card (nonogram): best_ms is the fastest recorded time across all board
  // sizes, so it is dominated by 5×5 blitz solves (a clean 5×5 records base −3s
  // purity bonus). The physical floor for a 5×5 (~13 fills at a hard ~150ms/fill
  // + scanning) is ~4-6s, and a strong expert blitz lands ~10-14s → records
  // ~7-11s. Top tier 9s ≈ a hard-but-provably-achievable clean expert blitz;
  // earlier tiers trace the casual→good→fast climb. A wrong fill adds +10s, so
  // the whole ladder rewards clean solving, not just speed.
  ...series({ id: 'punch-card-ms', name: 'Pixel Puncher', category: 'arcade', stat: gameStat('punch-card', 'best_ms'), thresholds: [90000, 45000, 25000, 15000, 9000], direction: 'low', blurb: (t) => `Clear a Punch Card in under ${ms(t)}.` }),
  // FreeCell Sprint (2026-07): best_ms is the fastest recorded clear across both
  // modes. A measured best-first bot solves random deals in ~106 moves; a competent
  // human clears in ~3-5 min, a strong player ~90-150s, and an expert keyboard
  // speed-runner (fast tap-to-move, no thrash) under a minute. Top tier 60s ≈ a
  // hard-but-provably-achievable expert speed-solve (~60% of the bot's move-optimal
  // ceiling driven at human tap speed); earlier tiers trace the casual→good→fast climb.
  ...series({ id: 'freecell-ms', name: 'Cascade Sprinter', category: 'arcade', stat: gameStat('freecell', 'best_ms'), thresholds: [420000, 240000, 150000, 90000, 60000], direction: 'low', blurb: (t) => `Clear a FreeCell deal in under ${ms(t)}.` }),

  // Daily puzzles.
  ...series({ id: 'daily-streak', name: 'Streak Keeper', category: 'daily', stat: DAILY.streakBest, thresholds: [3, 7, 14, 30, 60], topCosmetic: 'ach-daily', blurb: (t) => `Solve the daily puzzle ${t} days in a row.` }),
  // One daily puzzle on the floor, so a day gives one solve: 1 is the first
  // session, 7 a week, 30 a month, 100 a season and 250 most of a year.
  // The old 1,000 was three years.
  ...series({ id: 'daily-solved', name: 'Puzzler', category: 'daily', stat: DAILY.solved, thresholds: [1, 7, 30, 100, 250], blurb: (t) => `Solve ${t.toLocaleString()} daily ${t === 1 ? 'puzzle' : 'puzzles'}.` }),
  // Trick shot 2026-10: days cleared. Since rules 2 a day has unlimited
  // tries, so a clear is mostly coming back and keeping at it:
  // scripts/verify-trick-shot.ts' casual hand clears 85% of days within 20
  // tries (median 4), a good one 94% (median 2), weekends the misses. 1 is
  // the first clear, 5 a first week, 15 a first month, 40 a season of most
  // days, 100 about four months of every day. The tiers stay where the
  // single shot set them; earned tiers stay earned.
  ...series({ id: 'trick-shot-clears', name: 'Trick Shot', category: 'daily', stat: gameStat('trick-shot', 'clears'), thresholds: [1, 5, 15, 40, 100], blurb: (t) => `Clear ${t === 1 ? 'a trick shot table' : `${t} trick shot tables`}.` }),
  // Days in a row cleared (rules.ts trickShotStreak; a scratch on the last
  // ball isn't a clear). The steps are the daily puzzle streak's: 3 days, a
  // week, a fortnight, a month and two months. Every week has a hard
  // Saturday and an expert Sunday, so the longest run in a year of daily
  // play is about 10 for a first-go hand, 24 casual and 50 good
  // (scripts/verify-trick-shot.ts): 60 is a sharp player's.
  ...series({ id: 'trick-shot-streak', name: 'Hot cue', category: 'daily', stat: gameStat('trick-shot', 'best_streak'), thresholds: [3, 7, 14, 30, 60], blurb: (t) => `Clear trick shot ${t} days in a row.` }),
  // Mini golf 2026-10: holes in one in counted rounds (one a day). Tiers
  // from scripts/verify-mini-golf-replay.ts --full: holes in one a round are
  // 1.1 for a first-go hand, 1.8 casual, 2.6 good, 3.1 sharp. 1 is the
  // first, 10 a casual week, 30 a good player's fortnight, 100 a good
  // player's season, 250 a sharp player's twelve weeks.
  ...series({ id: 'mini-golf-aces', name: 'Hole in one', category: 'daily', stat: gameStat('mini-golf', 'aces'), thresholds: [1, 10, 30, 100, 250], blurb: (t) => `Sink ${t === 1 ? 'a hole in one' : `${t} holes in one`} in mini golf.` }),
  ...series({ id: 'pangram-finds', name: 'Lexicographer', category: 'daily', stat: gameStat('pangram', 'pangrams'), thresholds: [5, 25, 75, 200, 500], blurb: (t) => `Find ${t} pangrams.` }),

  // Multiplayer.
  // Multiplayer. Wins across every match game, bots included: the steps are
  // connect four's (1, 10, 40, 150, 500), since a mix of chess, 8-ball and
  // connect four wins a game in about 6 minutes on average. 500 wins is about
  // 50 hours of winning. The old top, 1,000, was 100.
  ...series({ id: 'mp-wins', name: 'Duelist', category: 'multiplayer', stat: MP.wins, thresholds: [1, 10, 40, 150, 500], topCosmetic: 'ach-duelist', blurb: (t) => `Win ${t.toLocaleString()} multiplayer ${t === 1 ? 'match' : 'matches'}.` }),
  // Streaks reset on any loss, bots included. At a win rate p over N games the
  // longest streak is about log(N (1 - p)) / log(1 / p): a player who wins
  // 70% of 100 games reaches 8, 75% of 200 reaches 14, 80% of 500 reaches 20.
  // 2 is a first session, 7 an even player's best in a month, 15 a strong
  // player's. 25 in a row is Untouchable, so 50 here only repeated it.
  ...series({ id: 'mp-streak', name: 'Unstoppable', category: 'multiplayer', stat: MP.winStreakBest, thresholds: [2, 4, 7, 10, 15], blurb: (t) => `Win ${t} matches in a row.` }),
  // The hard bot beats most players: scripts/sim-connect-four-thresholds.ts has
  // a good-or-better player taking 13 to 27% of games from it, so a first win
  // is a first week and not a first session (this series is a mastery track on
  // purpose). 100 wins is about 400 games, 15 hours. The old 500 was 75.
  ...series({ id: 'mp-bots', name: 'Giant Slayer', category: 'multiplayer', stat: MP.botHardWins, thresholds: [1, 3, 10, 30, 100], blurb: (t) => `Beat the hard bot ${t} time${t === 1 ? '' : 's'}.` }),
  // Chess and 8-ball wins are a count, so the tiers are set by time: a game
  // is about 12 minutes against a bot or a friend, and a player who wins half
  // of them spends about 25 minutes a win. 1 is the first session against the
  // easy bot, 5 a week, 20 a month, 60 about 25 hours and 150 about 60 hours
  // of play, a few months of a regular's evenings. The old top, 1,000 wins,
  // was 400 hours.
  ...series({ id: 'chess-wins', name: 'Grandmaster Path', category: 'multiplayer', stat: gameStat('chess', 'wins'), thresholds: [1, 5, 20, 60, 150], blurb: (t) => `Win ${t.toLocaleString()} chess ${t === 1 ? 'game' : 'games'}.` }),
  ...series({ id: '8ball-wins', name: 'Pool Shark', category: 'multiplayer', stat: gameStat('8-ball', 'wins'), thresholds: [1, 5, 20, 60, 150], blurb: (t) => `Win ${t.toLocaleString()} ${t === 1 ? 'game' : 'games'} of 8-ball.` }),
  // Connect Four 2026-10: wins are a count, so the tiers are set by time. Over
  // 30 games per pairing, scripts/sim-connect-four-thresholds.ts has a
  // good-or-better player (the bot's own search with 5-15% slips) beat the
  // easy bot 80-97% of the time and the medium and hard bots 13-27%, a game
  // taking 9-19 moves each. At 4 seconds a move, 500 wins is 5-7 hours against
  // the easy bot, 39-75 hours against the harder ones, and about 13 hours at an
  // even win rate against people. The ladder is chess's, with the top tier at
  // 500: a game here lasts a fifth as long.
  ...series({ id: 'connect-four-wins', name: 'Four in a Row', category: 'multiplayer', stat: gameStat('connect-four', 'wins'), thresholds: [1, 10, 40, 150, 500], blurb: (t) => `Win ${t.toLocaleString()} ${t === 1 ? 'game' : 'games'} of connect four.` }),
  // Bumper cars 2026-10: bumps you scored, over every round. A medium bot
  // lands 32 bumps a round and an easy one 26 (scripts/sim-bumper-cars.ts),
  // so 10 is the first round, 100 a first evening, 500 about 20 rounds, 2,000
  // a regular's few months and 6,000 about 200 rounds.
  ...series({ id: 'bumper-cars-bumps', name: 'Fender bender', category: 'multiplayer', stat: gameStat('bumper-cars', 'bumps'), thresholds: [10, 100, 500, 2000, 6000], blurb: (t) => `Land ${t.toLocaleString()} bumps in bumper cars.` }),
  ...series({ id: 'reversi-wins', name: 'Disc Dominator', category: 'multiplayer', stat: gameStat('reversi', 'wins'), thresholds: [1, 10, 50, 200, 1000], blurb: (t) => `Win ${t.toLocaleString()} games of Reversi.` }),
  ...series({ id: 'battleship-wins', name: 'Fleet Admiral', category: 'multiplayer', stat: gameStat('battleship', 'wins'), thresholds: [1, 10, 50, 200, 1000], blurb: (t) => `Win ${t.toLocaleString()} games of Battleship.` }),

  // Global / economy / dedication.
  // Every game counts, ticket machine rounds too (a drop is a game, 120 in 20
  // minutes), so a heavy machine session moves this faster than skill play.
  // A first session is 10 to 15 games, a regular's day is about 30. 3,000 is
  // 100 such days. The old 10,000 was a year of them, or 3 days of plinko.
  ...series({ id: 'global-games', name: 'Arcade Regular', category: 'global', stat: GLOBAL.games, thresholds: [10, 50, 250, 1000, 3000], topCosmetic: 'ach-regular', blurb: (t) => `Play ${t.toLocaleString()} games.` }),
  ...series({ id: 'global-streak', name: 'Daily Devotion', category: 'dedication', stat: GLOBAL.playStreakBest, thresholds: [3, 7, 30, 100, 365], topCosmetic: 'ach-devotion', blurb: (t) => `Play on ${t} days in a row.` }),
  // 1 hour is a first week of casual play, 5 a month, 20 a season, 60 a
  // regular's half year, 150 two hours a day for 75 days. The old 500 hours
  // was 250 days at two hours.
  ...series({ id: 'global-hours', name: 'Time Sink', category: 'dedication', stat: GLOBAL.playtimeMs, thresholds: [3600000, 18000000, 72000000, 216000000, 540000000], blurb: (t) => `Play for ${Math.round(t / 3600000)} ${t === 3600000 ? 'hour' : 'hours'}.` }),
  // Run tickets stop at 300 a day (375 on the featured game), and machine
  // payouts only count their net profit, so a day at the cap is the most a
  // player earns here. PROGRESSION.md: a 20 minute session reaches 300. 250 is
  // a first session, 1,500 five cap days, 6,000 twenty, 25,000 three months and
  // 90,000 a year of cap days. The old 1,000,000 was nine years.
  ...series({ id: 'economy-tickets', name: 'Ticket Tycoon', category: 'economy', stat: GLOBAL.ticketsEarned, thresholds: [250, 1500, 6000, 25000, 90000], topCosmetic: 'ach-tycoon', blurb: (t) => `Earn ${t.toLocaleString()} tickets in all.` }),
  // Items cost 400 to 2,000, 850 on average, and a regular earns about 580 a
  // day, so 3 items is a week, 15 about 3 months, 50 a year (42,500 tickets).
  // The old 150 was 135,000 tickets.
  ...series({ id: 'meta-collector', name: 'Collector', category: 'meta', stat: GLOBAL.cosmeticsOwned, thresholds: [3, 8, 15, 30, 50], blurb: (t) => `Own ${t} items from the counter.` }),
  // 132 achievements are listed. 90 is 68% of them, the five top tiers of a
  // dozen series and a few secrets away from all of them. The old 110 left
  // 17 to miss, secrets included, and the tiers of every other series to earn.
  ...series({ id: 'meta-achiever', name: 'Achiever', category: 'meta', stat: GLOBAL.achievementsUnlocked, thresholds: [10, 30, 50, 70, 90], topCosmetic: 'ach-achiever', blurb: (t) => `Unlock ${t} achievements.` }),
  // NOTE: a "Leaderboard Legend" track (#1 finishes) was removed pending a
  // reliable server-side rank-1 detection hook — GLOBAL.leaderboardTops has no
  // writer, so the series would have been permanently unobtainable.
];

// ── Standalone feats ────────────────────────────────────────────────────────
const STANDALONE: AchievementDef[] = [
  standalone({ id: 'first-game', name: 'Hello, World', description: 'Play a game.', category: 'meta', rarity: 'common', xp: 50, icon: 'first-game', condition: { stat: GLOBAL.games, gte: 1 } }),
  standalone({ id: 'jack-of-all', name: 'Jack of All Trades', description: 'Play 10 different games.', category: 'meta', rarity: 'rare', xp: 400, icon: 'jack-of-all', condition: { stat: GLOBAL.distinctGames, gte: 10 } }),
  standalone({ retired: true, id: 'arcade-master', name: 'Master of the Arcade', description: 'Play every game in the arcade.', category: 'meta', rarity: 'legendary', xp: 2500, icon: 'arcade-master', cosmeticId: 'ach-arcade-master', condition: { stat: GLOBAL.distinctGames, gte: 25 } }),
  standalone({ retired: true, id: 'flawless-typist', name: 'Flawless', description: 'Type 120+ WPM at 100% accuracy.', category: 'mastery', rarity: 'legendary', xp: 2000, icon: 'flawless', cosmeticId: 'ach-flawless', condition: { all: [{ stat: gameStat('typing-test', 'best_wpm'), gte: 120 }, { stat: gameStat('typing-test', 'best_accuracy'), gte: 100 }] } }),
  standalone({ retired: true, id: 'speed-demon', name: 'Speed Demon', description: 'React in under 180ms.', category: 'mastery', rarity: 'epic', xp: 1200, icon: 'speed-demon', condition: { stat: gameStat('reaction-time', 'best_ms'), lte: 180 } }),
  standalone({ retired: true, id: 'tetris-deity', name: 'Tetris Deity', description: 'Clear 100 four-line Tetrises.', category: 'mastery', rarity: 'legendary', xp: 2000, icon: 'tetris-deity', cosmeticId: 'ach-tetris-deity', condition: { stat: gameStat('tetris', 'tetrises'), gte: 100 } }),
  standalone({ id: '2048-ascendant', name: 'Beyond 2048', description: 'Reach the 4096 tile in 2048.', category: 'mastery', rarity: 'legendary', xp: 2000, icon: '2048-ascendant', condition: { stat: gameStat('2048', 'highest_tile'), gte: 4096 } }),
  standalone({ retired: true, id: 'high-roller', name: 'High Roller', description: 'Win 5,000 tickets in a single payout.', category: 'economy', rarity: 'epic', xp: 1000, icon: 'high-roller', condition: { stat: GLOBAL.biggestWin, gte: 5000 } }),
  standalone({ id: 'untouchable', name: 'Untouchable', description: 'Win 25 multiplayer matches in a row.', category: 'mastery', rarity: 'legendary', xp: 2500, icon: 'untouchable', cosmeticId: 'ach-untouchable', condition: { stat: MP.winStreakBest, gte: 25 } }),
  // Trick shot: the day's table cleared on the day's first try.
  // scripts/verify-trick-shot.ts: a hand that has read the line does it
  // about one day in 14 at first go, one in 7 casual, one in 3 good.
  { ...standalone({ id: 'trick-shot-first-try', name: 'Called it', description: 'Clear a trick shot table on the first try.', category: 'mastery', rarity: 'rare', xp: 500, condition: { stat: gameStat('trick-shot', 'first_try_clears'), gte: 1 } }), game: 'trick-shot' },
  standalone({ id: 'centurion', name: 'Centurion', description: 'Reach level 100.', category: 'meta', rarity: 'legendary', xp: 3000, icon: 'centurion', cosmeticId: 'ach-centurion', condition: { stat: GLOBAL.level, gte: 100 } }),
];

// "Play every game in <group>", one per floor group. Judged against the floor
// when it is evaluated: a game that leaves the floor stops counting, and a
// game that joins counts from the day it does.
const FLOOR_GROUP_FEATS: AchievementDef[] = ARCADE_FLOOR_GROUPS.map((group) => ({
  ...standalone({
    id: `group-${group.id}`,
    name: `every game: ${group.label}`,
    description: `Play every game in ${group.label}.`,
    category: 'meta',
    rarity: 'rare',
    xp: 400,
    icon: 'jack-of-all',
    condition: { stat: groupPlayedStat(group.id), gte: 1 },
  }),
  icon: badgeIconFor(`group-${group.id}`, 0, undefined, group.id),
  floorGroup: group.id,
}));

// ── Secret / easter-egg achievements ────────────────────────────────────────
const SECRETS: AchievementDef[] = [
  secret({ id: 'secret-konami', name: 'Cheat Codes', description: 'Type the Konami code on any page.', triggerKey: 'konami', rarity: 'epic', xp: 500, cosmeticId: 'ach-secret-konami', hint: 'A famous ten key sequence. Arrows first.' }),
  secret({ id: 'secret-logo', name: 'Stop Poking Me', description: 'Click the logo 10 times in a row, each within 2 seconds of the last.', triggerKey: 'logo', rarity: 'rare', xp: 250, hint: 'The logo at the top left has a short temper.' }),
  secret({ id: 'secret-night-owl', name: 'Night Owl', description: 'Finish a game between 3:00 and 3:59 in the morning, server time.', triggerKey: 'night_owl', rarity: 'rare', xp: 300, hint: 'Play when everyone else is asleep.' }),
  secret({ id: 'secret-early-bird', name: 'Early Bird', description: 'Finish a game between 5:00 and 5:59 in the morning, server time.', triggerKey: 'early_bird', rarity: 'rare', xp: 300, hint: 'Play before the sun is up.' }),
  secret({ id: 'secret-explorer', name: 'Cartographer', description: 'Open every game on the floor in one visit.', triggerKey: 'explorer', rarity: 'epic', xp: 600, hint: 'One browser tab, every cabinet on the floor.' }),
  secret({ retired: true, id: 'secret-lab', name: 'Behind the Curtain', description: 'Discover the hidden design lab.', triggerKey: 'lab', rarity: 'epic', xp: 500, hint: 'Not everything is on the map.' }),
  secret({ id: 'secret-humble', name: 'Humble Beginnings', description: 'Finish a run with a score of exactly 0.', triggerKey: 'humble', rarity: 'rare', xp: 200, hint: 'Some runs end before they start.' }),
  secret({ id: 'secret-window-shopper', name: 'Window Shopper', description: 'Open the counter 25 times without buying anything.', triggerKey: 'window_shopper', count: 25, rarity: 'rare', xp: 250, hint: 'Look at the prizes and keep your tickets.' }),
  secret({ id: 'secret-fashionista', name: 'Fashionista', description: 'Equip items 50 times.', triggerKey: 'fashionista', count: 50, rarity: 'rare', xp: 300, hint: 'Try everything on.' }),
  secret({ id: 'secret-palindrome', name: 'Palindrome', description: 'Finish a run with a score that reads the same backwards, at least 3 digits, like 404 or 1221.', triggerKey: 'palindrome', rarity: 'epic', xp: 500, hint: 'Look at your score in a mirror.' }),
  secret({ id: 'secret-leet', name: 'Elite', description: 'Finish a run with a score of 1337, or play for 13 hours and 37 minutes in all.', triggerKey: 'leet', rarity: 'epic', xp: 500, hint: 'Its score and its clock are the same number.' }),
  secret({ retired: true, id: 'secret-comeback', name: 'Comeback Kid', description: 'Win a match after trailing badly.', triggerKey: 'comeback', rarity: 'epic', xp: 600, hint: 'It is not over until it is over.' }),
  secret({ id: 'secret-marathon', name: 'One More Game', description: 'Play 20 games in one day.', triggerKey: 'marathon', count: 20, rarity: 'epic', xp: 700, hint: 'Twenty before midnight, server time.' }),
  secret({ id: 'secret-birthday', name: 'Many Happy Returns', description: 'Play a game on the day you made your account, a year or more later.', triggerKey: 'birthday', rarity: 'epic', xp: 800, cosmeticId: 'ach-secret-birthday', hint: 'Check the date you signed up.' }),
  secret({ id: 'secret-newyear', name: 'New Year, New High Score', description: 'Play a game on 1 January, server time.', triggerKey: 'newyear', rarity: 'epic', xp: 500, hint: 'The first day of the year.' }),
  secret({ id: 'secret-pi', name: 'Sweet, Sweet Pi', description: 'Finish a run with a score of 314, or play 314 games in all.', triggerKey: 'pi', rarity: 'rare', xp: 314, hint: 'A score, or a count of games. Three, one, four.' }),
  secret({ id: 'secret-rage-quit', name: 'Touch Grass', description: 'Leave a game within 5 seconds of opening it, 10 times.', triggerKey: 'rage_quit', count: 10, rarity: 'rare', xp: 200, hint: 'Walk away fast, and more than once.' }),
  // Completionist is evaluated specially by the engine (all non-secret unlocked),
  // not via a trigger counter — the sentinel condition never matches generically.
  standalone({ retired: true, id: 'secret-completionist', name: 'Gotta Get Them All', description: 'Unlock every non-secret achievement.', category: 'secret', rarity: 'legendary', xp: 5000, hidden: true, icon: 'secret', cosmeticId: 'ach-secret-completionist', hint: 'Leave no stone unturned.', condition: { stat: 'special.completionist', gte: 1 } }),
  secret({ id: 'secret-konami-master', name: 'Up Up Down Down', description: 'Type the Konami code 10 times.', triggerKey: 'konami', count: 10, rarity: 'legendary', xp: 1000, hint: 'Once was a start.' }),
  secret({ id: 'secret-lurker', name: 'Lurker', description: 'Open the profiles of 100 different players.', triggerKey: 'lurker', count: 100, rarity: 'rare', xp: 300, hint: 'Read about other players. A hundred of them.' }),
];

export const ACHIEVEMENTS: AchievementDef[] = [
  ...SERIES,
  ...STANDALONE,
  ...FLOOR_GROUP_FEATS,
  ...SECRETS,
];

/** Off the floor: not listed to anyone who hasn't earned it. A series follows
 *  its game, so a reserve game's series still unlocks for players who find it
 *  by link and lands on the retired shelf; if the game returns to the floor,
 *  the series is listed again. */
export function isRetiredAchievement(def: AchievementDef): boolean {
  if (def.retired) return true;
  return def.game !== undefined && !isOnFloor(def.game);
}

export const ACHIEVEMENTS_BY_ID: Map<string, AchievementDef> = new Map(
  ACHIEVEMENTS.map((a) => [a.id, a]),
);

/** Allowlist of valid secret trigger keys (for /api/achievements/trigger). */
export const SECRET_TRIGGER_KEYS: Set<string> = new Set(
  ACHIEVEMENTS.flatMap((a) => (a.secretTriggerKey ? [a.secretTriggerKey] : [])),
);

export function getAchievement(id: string): AchievementDef | undefined {
  return ACHIEVEMENTS_BY_ID.get(id);
}
