/**
 * Builds trick shot's bank of daily tables from the seeded generator.
 *
 *   npx tsx scripts/build-trick-shot-bank.ts --from 2026-10-04 --to 2027-12-31 --jobs 6
 *
 * Every day is generated by generateTrickShotPosition (deterministic from the
 * date), its solution is replayed once more before it is written, and the
 * bank goes to src/server/arcade/trick-shot-bank.json, sorted by date. Days
 * already in the bank are kept unless --force. The server reads the bank and
 * only generates a day itself when the bank has run out.
 *
 * scripts/verify-trick-shot.ts checks the bank: every solution clears, and a
 * sample of days regenerates exactly.
 */
import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  generateTrickShotPosition,
  TRICK_SHOT_GENERATOR_VERSION,
} from '../src/features/arcade/lib/trick-shot/generator';
import { playTrickShot } from '../src/features/arcade/lib/trick-shot/shot';
import { toBankedDay, type BankedDay, type TrickShotBank } from '../src/server/arcade/trick-shot';

const BANK_PATH = path.join(process.cwd(), 'src/server/arcade/trick-shot-bank.json');

const arg = (name: string, fallback?: string) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : fallback;
};

function daysBetween(from: string, to: string): string[] {
  const out: string[] = [];
  for (let t = Date.parse(`${from}T00:00:00Z`); t <= Date.parse(`${to}T00:00:00Z`); t += 86_400_000) {
    out.push(new Date(t).toISOString().slice(0, 10));
  }
  return out;
}

function buildDay(key: string): BankedDay {
  const position = generateTrickShotPosition(key);
  const replay = playTrickShot(position.balls, position.solution);
  if (!replay.clear) throw new Error(`${key}: the solution does not clear on replay`);
  return toBankedDay(position);
}

// A worker builds the days it is given and prints one JSON line per day.
if (process.argv.includes('--worker')) {
  const keys = (arg('days') ?? '').split(',').filter(Boolean);
  for (const key of keys) {
    process.stdout.write(`${JSON.stringify({ key, day: buildDay(key) })}\n`);
  }
  process.exit(0);
}

const from = arg('from', '2026-10-04')!;
const to = arg('to', '2027-12-31')!;
const jobs = Math.max(1, Number(arg('jobs', '4')));
const force = process.argv.includes('--force');

let bank: TrickShotBank = { version: TRICK_SHOT_GENERATOR_VERSION, days: {} };
try {
  const existing = JSON.parse(readFileSync(BANK_PATH, 'utf8')) as TrickShotBank;
  if (existing.version === TRICK_SHOT_GENERATOR_VERSION) bank = existing;
} catch {
  /* a new bank */
}

const wanted = daysBetween(from, to).filter((key) => force || !bank.days[key]);
console.log(`building ${wanted.length} days with ${jobs} workers`);
const started = Date.now();

const slices: string[][] = Array.from({ length: jobs }, () => []);
wanted.forEach((key, i) => slices[i % jobs]!.push(key));

await Promise.all(
  slices
    .filter((slice) => slice.length > 0)
    .map(
      (slice) =>
        new Promise<void>((resolve, reject) => {
          const child = spawn(
            process.execPath,
            [...process.execArgv, process.argv[1]!, '--worker', '--days', slice.join(',')],
            { stdio: ['ignore', 'pipe', 'inherit'] },
          );
          let buffer = '';
          child.stdout.on('data', (chunk: Buffer) => {
            buffer += chunk.toString();
            let nl = buffer.indexOf('\n');
            while (nl >= 0) {
              const line = buffer.slice(0, nl);
              buffer = buffer.slice(nl + 1);
              const { key, day } = JSON.parse(line) as { key: string; day: BankedDay };
              bank.days[key] = day;
              nl = buffer.indexOf('\n');
            }
          });
          child.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`worker exited ${code}`))));
        }),
    ),
);

const sorted: TrickShotBank = {
  version: TRICK_SHOT_GENERATOR_VERSION,
  days: Object.fromEntries(Object.entries(bank.days).sort(([a], [b]) => a.localeCompare(b))),
};
// One day per line keeps the diff readable.
const lines = Object.entries(sorted.days).map(([key, day]) => `    ${JSON.stringify(key)}: ${JSON.stringify(day)}`);
writeFileSync(BANK_PATH, `{\n  "version": ${sorted.version},\n  "days": {\n${lines.join(',\n')}\n  }\n}\n`);
console.log(`wrote ${lines.length} days in ${((Date.now() - started) / 1000).toFixed(0)}s`);
