export const CHESS_WAGER_INCREMENT = 5;
export const CHESS_WAGER_MIN = 5;
export const CHESS_CHALLENGE_MAX_WAGER = 1000;
export const CHESS_TOURNAMENT_DEFAULT_MIN_BET = CHESS_WAGER_MIN;
export const CHESS_TOURNAMENT_DEFAULT_MAX_BET = 100;
