/**
 * Server-only Sudoku generator + solver + validator (pure, deterministic).
 *
 * Anti-cheat contract:
 *  - The SOLUTION never leaves the server. The puzzle route returns only the
 *    81-cell `givens` array (0 = blank). The score route regenerates the
 *    puzzle+solution from the SAME seed+difficulty and verifies the player's
 *    submitted grid equals the unique solution.
 *  - Everything here is a pure function of (seed, difficulty) — no Date.now(),
 *    no Math.random() — so the puzzle route and the score route always agree.
 *
 * A board is a flat `number[]` of length 81 (row-major), values 0..9 where 0
 * means an empty cell. Rows/cols are 0..8; boxes are the nine 3×3 blocks.
 *
 * Generation:
 *  1. Build a full, valid solved grid by seeded-shuffling a canonical base
 *     grid (digit relabel + band/stack/row/col permutations preserve validity).
 *  2. Punch holes in a 180°-symmetric order, only removing a cell (pair) while
 *     the puzzle stays UNIQUELY solvable, until the difficulty's blank target
 *     is met (or no further symmetric removal keeps uniqueness).
 *
 * Uniqueness is enforced with a solution-counting backtracking solver capped
 * at 2 (we never need the exact count, only "exactly one" vs "more than one").
 */

export type SudokuDifficulty = 'easy' | 'medium' | 'hard' | 'expert' | 'evil';

export const SUDOKU_DIFFICULTIES: readonly SudokuDifficulty[] = [
  'easy',
  'medium',
  'hard',
  'expert',
  'evil',
] as const;

export function isSudokuDifficulty(value: unknown): value is SudokuDifficulty {
  return (
    typeof value === 'string' &&
    (SUDOKU_DIFFICULTIES as readonly string[]).includes(value)
  );
}

/**
 * Target number of BLANK cells per difficulty tier. Higher tiers dig more
 * holes (fewer givens) which, with the symmetric unique-solution constraint,
 * forces harder logic. These are upper targets — the generator stops early if
 * no further symmetric removal preserves a unique solution, so the realized
 * blank count for a given seed may be a touch lower (always still unique).
 *
 *   easy   : ~43 givens (38 blanks)
 *   medium : ~36 givens (45 blanks)
 *   hard   : ~31 givens (50 blanks)
 *   expert : ~28 givens (53 blanks)
 *   evil   : ~25 givens (56 blanks)
 */
const BLANK_TARGET: Record<SudokuDifficulty, number> = {
  easy: 38,
  medium: 45,
  hard: 50,
  expert: 53,
  evil: 56,
};

export function blankTargetFor(difficulty: SudokuDifficulty): number {
  return BLANK_TARGET[difficulty];
}

/**
 * Simple seeded PRNG (mulberry32) — identical implementation to the one used
 * by the typing test, so seeding behavior is consistent across the codebase.
 * Deterministic 32-bit-seeded pseudo-random in [0, 1).
 */
function seededRandom(seed: number): () => number {
  let s = seed | 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Deterministic Fisher–Yates shuffle of a copied array. */
function shuffled<T>(arr: readonly T[], rng: () => number): T[] {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = out[i]!;
    out[i] = out[j]!;
    out[j] = tmp;
  }
  return out;
}

const idx = (r: number, c: number) => r * 9 + c;

/**
 * Canonical solved Sudoku grid generated by the standard "shift rows by box"
 * pattern. Valid by construction; we then permute it deterministically so the
 * realized full grid depends on the seed.
 */
function baseSolvedGrid(): number[] {
  const grid = new Array<number>(81).fill(0);
  for (let r = 0; r < 9; r += 1) {
    for (let c = 0; c < 9; c += 1) {
      // Classic pattern: value = (3*(r%3) + floor(r/3) + c) mod 9 + 1
      const v = ((3 * (r % 3) + Math.floor(r / 3) + c) % 9) + 1;
      grid[idx(r, c)] = v;
    }
  }
  return grid;
}

/**
 * Produce a seeded full solved grid by applying validity-preserving symmetries
 * to the canonical grid:
 *   - relabel digits (a permutation of 1..9)
 *   - permute the three bands (row-blocks) and the rows within each band
 *   - permute the three stacks (col-blocks) and the cols within each stack
 *   - optional transpose
 * All of these keep the grid a valid Sudoku solution.
 */
function generateFullSolution(rng: () => number): number[] {
  const base = baseSolvedGrid();

  // Digit relabeling: map original digit d -> digitMap[d].
  const digitPerm = shuffled([1, 2, 3, 4, 5, 6, 7, 8, 9], rng);
  const digitMap = new Array<number>(10).fill(0);
  for (let d = 1; d <= 9; d += 1) digitMap[d] = digitPerm[d - 1]!;

  // Row permutation: permute bands, then rows within each band.
  const bandOrder = shuffled([0, 1, 2], rng);
  const rowOrder = new Array<number>(9);
  for (let b = 0; b < 3; b += 1) {
    const within = shuffled([0, 1, 2], rng);
    for (let k = 0; k < 3; k += 1) {
      rowOrder[b * 3 + k] = bandOrder[b]! * 3 + within[k]!;
    }
  }

  // Column permutation: permute stacks, then cols within each stack.
  const stackOrder = shuffled([0, 1, 2], rng);
  const colOrder = new Array<number>(9);
  for (let s = 0; s < 3; s += 1) {
    const within = shuffled([0, 1, 2], rng);
    for (let k = 0; k < 3; k += 1) {
      colOrder[s * 3 + k] = stackOrder[s]! * 3 + within[k]!;
    }
  }

  const transpose = rng() < 0.5;

  const out = new Array<number>(81).fill(0);
  for (let r = 0; r < 9; r += 1) {
    for (let c = 0; c < 9; c += 1) {
      const srcR = rowOrder[r]!;
      const srcC = colOrder[c]!;
      const v = digitMap[base[idx(srcR, srcC)]!]!;
      if (transpose) {
        out[idx(c, r)] = v;
      } else {
        out[idx(r, c)] = v;
      }
    }
  }
  return out;
}

/**
 * Counts solutions of a partially-filled board, short-circuiting once `cap`
 * solutions have been found (we only ever care about "exactly one"). Uses
 * MRV (minimum-remaining-values) cell selection + bitmask candidate tracking
 * for speed. Operates on a copy; never mutates the input.
 */
export function countSolutions(board: readonly number[], cap = 2): number {
  const cells = board.slice();

  // Bitmask of used digits per row / col / box (bit d set => digit d present).
  const rowMask = new Array<number>(9).fill(0);
  const colMask = new Array<number>(9).fill(0);
  const boxMask = new Array<number>(9).fill(0);
  const boxOf = (r: number, c: number) => Math.floor(r / 3) * 3 + Math.floor(c / 3);

  for (let r = 0; r < 9; r += 1) {
    for (let c = 0; c < 9; c += 1) {
      const v = cells[idx(r, c)]!;
      if (v !== 0) {
        const bit = 1 << v;
        rowMask[r]! |= bit;
        colMask[c]! |= bit;
        boxMask[boxOf(r, c)]! |= bit;
      }
    }
  }

  let count = 0;

  const solve = (): void => {
    if (count >= cap) return;

    // Find the empty cell with the fewest candidates (MRV).
    let bestPos = -1;
    let bestCandidates = 0;
    let bestCount = 10;
    for (let r = 0; r < 9; r += 1) {
      for (let c = 0; c < 9; c += 1) {
        const p = idx(r, c);
        if (cells[p] !== 0) continue;
        const used = rowMask[r]! | colMask[c]! | boxMask[boxOf(r, c)]!;
        // candidate digits 1..9 are bits 1..9; ~used masked to that range.
        const candidates = ~used & 0b1111111110;
        if (candidates === 0) {
          // Dead end — this branch yields no solutions.
          return;
        }
        const n = popcount(candidates);
        if (n < bestCount) {
          bestCount = n;
          bestPos = p;
          bestCandidates = candidates;
          if (n === 1) break;
        }
      }
      if (bestCount === 1) break;
    }

    if (bestPos === -1) {
      // No empty cells: a complete, valid solution.
      count += 1;
      return;
    }

    const r = Math.floor(bestPos / 9);
    const c = bestPos % 9;
    const box = boxOf(r, c);
    let bits = bestCandidates;
    while (bits !== 0 && count < cap) {
      const lowest = bits & -bits;
      const v = Math.log2(lowest) | 0;
      bits &= bits - 1;

      const bit = 1 << v;
      cells[bestPos] = v;
      rowMask[r]! |= bit;
      colMask[c]! |= bit;
      boxMask[box]! |= bit;

      solve();

      cells[bestPos] = 0;
      rowMask[r]! &= ~bit;
      colMask[c]! &= ~bit;
      boxMask[box]! &= ~bit;
    }
  };

  solve();
  return count;
}

function popcount(n: number): number {
  let x = n;
  let count = 0;
  while (x !== 0) {
    x &= x - 1;
    count += 1;
  }
  return count;
}

/**
 * Solves a board, returning the (first) full solution or null if unsolvable.
 * Deterministic: fills empty cells in MRV order trying digits ascending.
 */
export function solveSudoku(board: readonly number[]): number[] | null {
  const cells = board.slice();
  const rowMask = new Array<number>(9).fill(0);
  const colMask = new Array<number>(9).fill(0);
  const boxMask = new Array<number>(9).fill(0);
  const boxOf = (r: number, c: number) => Math.floor(r / 3) * 3 + Math.floor(c / 3);

  for (let r = 0; r < 9; r += 1) {
    for (let c = 0; c < 9; c += 1) {
      const v = cells[idx(r, c)]!;
      if (v !== 0) {
        const bit = 1 << v;
        if (
          (rowMask[r]! & bit) !== 0 ||
          (colMask[c]! & bit) !== 0 ||
          (boxMask[boxOf(r, c)]! & bit) !== 0
        ) {
          // Givens already conflict — unsolvable.
          return null;
        }
        rowMask[r]! |= bit;
        colMask[c]! |= bit;
        boxMask[boxOf(r, c)]! |= bit;
      }
    }
  }

  const solve = (): boolean => {
    let bestPos = -1;
    let bestCandidates = 0;
    let bestCount = 10;
    for (let r = 0; r < 9; r += 1) {
      for (let c = 0; c < 9; c += 1) {
        const p = idx(r, c);
        if (cells[p] !== 0) continue;
        const used = rowMask[r]! | colMask[c]! | boxMask[boxOf(r, c)]!;
        const candidates = ~used & 0b1111111110;
        if (candidates === 0) return false;
        const n = popcount(candidates);
        if (n < bestCount) {
          bestCount = n;
          bestPos = p;
          bestCandidates = candidates;
          if (n === 1) break;
        }
      }
      if (bestCount === 1) break;
    }

    if (bestPos === -1) return true; // solved

    const r = Math.floor(bestPos / 9);
    const c = bestPos % 9;
    const box = boxOf(r, c);
    let bits = bestCandidates;
    while (bits !== 0) {
      const lowest = bits & -bits;
      const v = Math.log2(lowest) | 0;
      bits &= bits - 1;

      const bit = 1 << v;
      cells[bestPos] = v;
      rowMask[r]! |= bit;
      colMask[c]! |= bit;
      boxMask[box]! |= bit;

      if (solve()) return true;

      cells[bestPos] = 0;
      rowMask[r]! &= ~bit;
      colMask[c]! &= ~bit;
      boxMask[box]! &= ~bit;
    }
    return false;
  };

  return solve() ? cells : null;
}

export interface GeneratedSudoku {
  /** 81-cell givens array, 0 = blank. Safe to send to the client. */
  puzzle: number[];
  /** 81-cell full solution. SERVER-ONLY — never send to the client. */
  solution: number[];
  difficulty: SudokuDifficulty;
  /** Realized number of blanks (givens = 81 - blanks). */
  blanks: number;
}

/**
 * Generates a uniquely-solvable puzzle for `(seed, difficulty)`.
 *
 * Deterministic: identical output for identical inputs. Dig order is a
 * seeded shuffle of the 41 cells at indices 0..40 (each paired with its 180°
 * partner 80-i); the center cell (40) is its own partner. A cell pair is only
 * cleared if the puzzle remains uniquely solvable afterwards.
 */
export function generateSudoku(
  seed: number,
  difficulty: SudokuDifficulty,
): GeneratedSudoku {
  const rng = seededRandom(seed >>> 0);
  const solution = generateFullSolution(rng);
  const puzzle = solution.slice();

  const target = BLANK_TARGET[difficulty];

  // Symmetric (180°) removal order over the 41 "first-half" cells (0..40).
  const firstHalf: number[] = [];
  for (let i = 0; i <= 40; i += 1) firstHalf.push(i);
  const order = shuffled(firstHalf, rng);

  let blanks = 0;
  for (const i of order) {
    if (blanks >= target) break;
    const j = 80 - i;

    if (i === j) {
      // Center cell — single removal.
      if (puzzle[i] === 0) continue;
      const saved = puzzle[i]!;
      puzzle[i] = 0;
      if (countSolutions(puzzle, 2) === 1) {
        blanks += 1;
      } else {
        puzzle[i] = saved;
      }
      continue;
    }

    if (puzzle[i] === 0 && puzzle[j] === 0) continue;
    const savedI = puzzle[i]!;
    const savedJ = puzzle[j]!;
    puzzle[i] = 0;
    puzzle[j] = 0;
    if (countSolutions(puzzle, 2) === 1) {
      blanks += 2;
    } else {
      puzzle[i] = savedI;
      puzzle[j] = savedJ;
    }
  }

  return { puzzle, solution, difficulty, blanks };
}

/**
 * True iff `board` is a fully-filled, fully-valid Sudoku grid (every cell
 * 1..9 with no duplicate in any row, column, or 3×3 box).
 */
export function isCompleteValidGrid(board: readonly number[]): boolean {
  if (board.length !== 81) return false;
  const boxOf = (r: number, c: number) => Math.floor(r / 3) * 3 + Math.floor(c / 3);
  const rowMask = new Array<number>(9).fill(0);
  const colMask = new Array<number>(9).fill(0);
  const boxMask = new Array<number>(9).fill(0);

  for (let r = 0; r < 9; r += 1) {
    for (let c = 0; c < 9; c += 1) {
      const v = board[idx(r, c)];
      if (typeof v !== 'number' || !Number.isInteger(v) || v < 1 || v > 9) {
        return false;
      }
      const bit = 1 << v;
      const b = boxOf(r, c);
      if (
        (rowMask[r]! & bit) !== 0 ||
        (colMask[c]! & bit) !== 0 ||
        (boxMask[b]! & bit) !== 0
      ) {
        return false;
      }
      rowMask[r]! |= bit;
      colMask[c]! |= bit;
      boxMask[b]! |= bit;
    }
  }
  return true;
}

/**
 * Validates a submitted solution against a puzzle's givens. The submission is
 * accepted iff:
 *   (a) it is a complete, valid Sudoku grid, AND
 *   (b) it keeps every given cell unchanged (consistency with the puzzle).
 *
 * Because a properly-generated puzzle has a UNIQUE solution, (a)+(b) together
 * imply the submission equals that unique solution — but the score route also
 * checks equality against the regenerated `solution` explicitly for defense in
 * depth.
 */
export function isValidSolution(
  givens: readonly number[],
  attempt: readonly number[],
): boolean {
  if (givens.length !== 81 || attempt.length !== 81) return false;
  if (!isCompleteValidGrid(attempt)) return false;
  for (let i = 0; i < 81; i += 1) {
    const g = givens[i]!;
    if (g !== 0 && attempt[i] !== g) return false;
  }
  return true;
}

/** Strict equality of two 81-cell boards. */
export function gridsEqual(a: readonly number[], b: readonly number[]): boolean {
  if (a.length !== 81 || b.length !== 81) return false;
  for (let i = 0; i < 81; i += 1) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

/**
 * Coerces an unknown payload into a clean 81-cell `number[]` of integers 0..9,
 * or returns null if the shape is wrong. Used by the score route to sanitize
 * the client-submitted solution before validating it.
 */
export function normalizeBoard(value: unknown): number[] | null {
  if (!Array.isArray(value) || value.length !== 81) return null;
  const out = new Array<number>(81);
  for (let i = 0; i < 81; i += 1) {
    const v = value[i];
    if (typeof v !== 'number' || !Number.isInteger(v) || v < 0 || v > 9) {
      return null;
    }
    out[i] = v;
  }
  return out;
}
