export type TrackId =
  | 'classic'
  | 'synthwave'
  | 'chiptune'
  | 'ambient'
  | 'orchestral'
  | 'edm-bass'
  | 'off';

export const TRACKS: { id: TrackId; name: string }[] = [
  { id: 'classic', name: 'Classic' },
  { id: 'synthwave', name: 'Synthwave' },
  { id: 'chiptune', name: 'Chiptune' },
  { id: 'ambient', name: 'Ambient' },
  { id: 'orchestral', name: 'Orchestral' },
  { id: 'edm-bass', name: 'EDM Bass Boost' },
  { id: 'off', name: 'Off' },
];

const NOTE_FREQ: Record<string, number> = {
  C3: 130.81,
  D3: 146.83,
  E3: 164.81,
  F3: 174.61,
  G3: 196.0,
  A3: 220.0,
  B3: 246.94,
  C4: 261.63,
  D4: 293.66,
  E4: 329.63,
  F4: 349.23,
  G4: 392.0,
  A4: 440.0,
  B4: 493.88,
  C5: 523.25,
  D5: 587.33,
  E5: 659.25,
  F5: 698.46,
  G5: 783.99,
  A5: 880.0,
  B5: 987.77,
  'G#5': 830.61,
  'G#3': 207.65,
  'G#4': 415.3,
  Bb3: 233.08,
  Bb4: 466.16,
  'F#3': 185.0,
  'F#4': 369.99,
  Eb3: 155.56,
  Eb4: 311.13,
  Ab3: 207.65,
  Ab4: 415.3,
  Db4: 277.18,
};

export function n(note: string): number {
  return NOTE_FREQ[note] ?? 440;
}

export type TrackNote = {
  time: number;
  freq: number;
  freqEnd?: number;
  dur: number;
  wave: OscillatorType;
  vol: number;
  /** Explicit stereo pan position (-1 = full left, +1 = full right).
   *  When omitted, the music manager assigns a random pan from the track FX profile. */
  pan?: number;
};
export type TrackData = { duration: number; notes: TrackNote[] };
export type StepNote = [note: string | null, steps: number];
export type NoteRole = 'kick' | 'bass' | 'melody' | 'harmony' | 'perc' | 'fx';

export const TETRIS_THEME_BPM = 149.86;
export const TETRIS_THEME_PHRASE_A: StepNote[] = [
  ['E5', 2],
  ['B4', 1],
  ['C5', 1],
  ['D5', 2],
  ['C5', 1],
  ['B4', 1],
  ['A4', 2],
  ['A4', 1],
  ['C5', 1],
  ['E5', 2],
  ['D5', 1],
  ['C5', 1],
  ['B4', 3],
  ['C5', 1],
  ['D5', 2],
  ['E5', 2],
  ['C5', 2],
  ['A4', 2],
  ['A4', 4],
];
export const TETRIS_THEME_PHRASE_B: StepNote[] = [
  ['D5', 3],
  ['F5', 1],
  ['A5', 2],
  ['G5', 1],
  ['F5', 1],
  ['E5', 3],
  ['C5', 1],
  ['E5', 2],
  ['D5', 1],
  ['C5', 1],
  ['B4', 2],
  ['B4', 1],
  ['C5', 1],
  ['D5', 2],
  ['E5', 2],
  ['C5', 2],
  ['A4', 2],
  ['A4', 4],
];
export const TETRIS_THEME_PHRASE_C: StepNote[] = [
  ['E5', 2],
  ['C5', 2],
  ['D5', 2],
  ['B4', 2],
  ['C5', 2],
  ['A4', 2],
  ['G#4', 2],
  ['B4', 2],
  ['E5', 2],
  ['C5', 2],
  ['D5', 2],
  ['B4', 2],
  ['C5', 2],
  ['E5', 2],
  ['A5', 2],
  ['A5', 1],
  ['G#5', 1],
];
export const TETRIS_THEME_PHRASE_A_BRIDGE: StepNote[] = [
  ['E5', 2],
  ['B4', 1],
  ['C5', 1],
  ['D5', 2],
  ['C5', 1],
  ['B4', 1],
  ['A4', 2],
  ['C5', 1],
  ['E5', 1],
  ['F5', 1],
  ['E5', 1],
  ['D5', 1],
  ['C5', 2],
  ['B4', 2],
  ['C5', 1],
  ['D5', 1],
  ['E5', 2],
  ['G5', 1],
  ['F5', 1],
  ['E5', 2],
  ['D5', 1],
  ['C5', 1],
  ['B4', 1],
  ['A4', 2],
];
export const TETRIS_THEME_PHRASE_B_BRIDGE: StepNote[] = [
  ['D5', 2],
  ['F5', 1],
  ['A5', 1],
  ['G5', 2],
  ['F5', 1],
  ['E5', 1],
  ['C5', 2],
  ['E5', 1],
  ['G5', 1],
  ['F5', 2],
  ['E5', 1],
  ['D5', 1],
  ['C5', 2],
  ['B4', 2],
  ['C5', 2],
  ['D5', 2],
  ['F5', 1],
  ['E5', 1],
  ['D5', 2],
  ['C5', 2],
  ['B4', 2],
];
export const TETRIS_THEME_PHRASE_C_BRIDGE: StepNote[] = [
  ['E5', 2],
  ['C5', 2],
  ['D5', 2],
  ['B4', 2],
  ['C5', 1],
  ['D5', 1],
  ['E5', 2],
  ['G5', 2],
  ['F5', 2],
  ['E5', 2],
  ['D5', 2],
  ['C5', 2],
  ['B4', 2],
  ['A4', 2],
  ['G#4', 2],
  ['B4', 2],
  ['C5', 1],
  ['E5', 1],
];
export const TETRIS_THEME_BASS_A: StepNote[] = [
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['C4', 2],
  ['E3', 2],
  ['B3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
];
export const TETRIS_THEME_BASS_B: StepNote[] = [
  ['D3', 2],
  ['A3', 2],
  ['D3', 2],
  ['A3', 2],
  ['C3', 2],
  ['G3', 2],
  ['C3', 2],
  ['G3', 2],
  ['B3', 2],
  ['F3', 2],
  ['B3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
];
export const TETRIS_THEME_BASS_C: StepNote[] = [
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['Eb3', 2],
  ['B3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
];
export const TETRIS_THEME_BASS_A_BRIDGE: StepNote[] = [
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['F3', 2],
  ['C4', 2],
  ['F3', 2],
  ['E3', 2],
  ['D3', 2],
  ['A3', 2],
  ['E3', 2],
  ['B3', 2],
  ['C4', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
];
export const TETRIS_THEME_BASS_B_BRIDGE: StepNote[] = [
  ['D3', 2],
  ['A3', 2],
  ['F3', 2],
  ['C4', 2],
  ['E3', 2],
  ['B3', 2],
  ['E3', 2],
  ['B3', 2],
  ['C3', 2],
  ['G3', 2],
  ['C3', 2],
  ['G3', 2],
  ['B3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
];
export const TETRIS_THEME_BASS_C_BRIDGE: StepNote[] = [
  ['A3', 2],
  ['E3', 2],
  ['A3', 2],
  ['E3', 2],
  ['G3', 2],
  ['D3', 2],
  ['G3', 2],
  ['D3', 2],
  ['F3', 2],
  ['C4', 2],
  ['F3', 2],
  ['C4', 2],
  ['E3', 2],
  ['B3', 2],
  ['A3', 2],
  ['E3', 2],
];
type ThemeSection = { melody: StepNote[]; bass: StepNote[] };
export const TETRIS_THEME_ORIGINAL_FORM: ThemeSection[] = [
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
];

// Track-specific extended arrangements so each style has different bridge
// placement and melodic variation over the longer loop.
export const TETRIS_THEME_SYNTHWAVE_FORM: ThemeSection[] = [
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_A_BRIDGE, bass: TETRIS_THEME_BASS_A_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_C_BRIDGE, bass: TETRIS_THEME_BASS_C_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_B_BRIDGE, bass: TETRIS_THEME_BASS_B_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_A_BRIDGE, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
];
export const TETRIS_THEME_CHIPTUNE_FORM: ThemeSection[] = [
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_A_BRIDGE, bass: TETRIS_THEME_BASS_A_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_C_BRIDGE, bass: TETRIS_THEME_BASS_C_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_A_BRIDGE, bass: TETRIS_THEME_BASS_A_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_B_BRIDGE, bass: TETRIS_THEME_BASS_B_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_C_BRIDGE, bass: TETRIS_THEME_BASS_C_BRIDGE },
];
export const TETRIS_THEME_ORCHESTRAL_FORM: ThemeSection[] = [
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_A_BRIDGE, bass: TETRIS_THEME_BASS_A_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_B_BRIDGE, bass: TETRIS_THEME_BASS_B_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_C_BRIDGE, bass: TETRIS_THEME_BASS_C_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_C, bass: TETRIS_THEME_BASS_C },
  { melody: TETRIS_THEME_PHRASE_B, bass: TETRIS_THEME_BASS_B },
  { melody: TETRIS_THEME_PHRASE_A_BRIDGE, bass: TETRIS_THEME_BASS_A },
  { melody: TETRIS_THEME_PHRASE_C_BRIDGE, bass: TETRIS_THEME_BASS_C_BRIDGE },
  { melody: TETRIS_THEME_PHRASE_A, bass: TETRIS_THEME_BASS_A },
];
